//import list_items from "./listData";
// get list data
// component in the app
import ListButtons from "../List-buttons/listButtons.js";
import "./list.css";
/**
 * Imports needed: CSS (style), ListButtons (component that includes the delete, edit, done buttons)
 * This function takes the props of each item on the list as an object:
 * @param {object} props - the following props:
 * key: NOT IN USE. Generated by uuidv4()
 * title: string - name of the to do 
 * to_do_id: number - id of the to do item
 * user_id: number - id of the user
 * done: boolean - task completed or not
 * priority: dropdown:
 *    - value="" Select Priority
 *    - value="1" Top
 *    - value="2" Medium
 *    - value="3" Low
 * date_created: NOT IN USE. Date - when to do was created
 * date_completed: NOT IN USE. Date - when to do is completed
 * due_date: NOT IN USE. Date - when to do is due
 * handleDeleteClick - function that updates the setState by deleting an item from the list finding it with its id
 * handleDoneClick - function that updates the setState by crossing an item as done from the list finding it with its id
 * id: number - index created when listDataState was mapped in App.js
 * doneState: NOT IN USE. See App.js
 * @returns 
 * The items in the ToDo list
 * Done, Edit and Delete buttons next to them 
 */

function ListItems({
  key,
  title,
  to_do_id,
  user_id,
  done,
  priority,
  date_created,
  date_completed,
  due_date,
  handleDeleteClick,
  handleDoneClick,
  id,
  doneState,
  listDataState
})  { 
    // console.log("This is the OBJECT", listDataState);
    // console.log("This is the TITLE", title);
    if(done === false){
      return (
      <tr className="items" id="toDoTitle">
        <td
          key={key}
          to_do_id={to_do_id}
          user_id={user_id}
          done={done}
          priority={priority}
          date_created={date_created}
          date_completed={date_completed}
          due_date={due_date}
          id={id}
      >
          <p>{title}</p>
        </td>
        <td>
          <ListButtons
          handleDeleteClick={handleDeleteClick}
          to_do_id={to_do_id}
          handleDoneClick={handleDoneClick}
          id={id}
        />
        </td>
      </tr>
  );} 
  
  if (done === true){
    return (
      <tr className="items" id="toDoTitleDone">
        <td
          key={key}
          to_do_id={to_do_id}
          user_id={user_id}
          done={done}
          priority={priority}
          date_created={date_created}
          date_completed={date_completed}
          due_date={due_date}
          id={id}
        >
          {title}
        </td>
        <td>
          <ListButtons
            handleDeleteClick={handleDeleteClick}
            to_do_id={to_do_id}
            handleDoneClick={handleDoneClick}
            id={id}
          />
        </td>
      </tr>
    );}
}

export default ListItems;
